### ISSUE TITLE
Reputation items filter not working in French

### ISSUE THREAD

**Issue by bernardthibaut** [Wutname1/BetterBags-Openable#2]
Hi! :)

I noticed that the reputation items were not correctly detected in my game which is in French. The text you are looking for is _" point de réputation auprès de "_ but it seems that it only match with only a few items (as seen [here in that Wowhead search](https://www.wowhead.com/fr/items/consumables?filter=107;0;point+de+r%C3%A9putation+aupr%C3%A8s+de#0+1+19)).

I think a better text to search for would be _" réputation envers "_ and _" réputation auprès "_. It would have be easier if Blizzard was more consistent.

And by the way, there is a missing character in the filter mode in the settings of the plugin: "Reputaion Gain Items".

Thanks for the addon and have a good day ;)

**Comment by Wutname1** [comment]
Ya, the multiple wordings of things is annoying to say the least. Let me know if you find more.
